# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-03 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='\u65e5\u671f')),
                ('title', models.CharField(default='', max_length=20, verbose_name='\u6807\u9898')),
                ('content', models.TextField(default='', max_length=1000, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb',
                'verbose_name_plural': '\u65b0\u95fb',
            },
        ),
    ]
