# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_images_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='\u7559\u8a00\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(max_length=30, verbose_name='\u7535\u5b50\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=30, verbose_name='\u4e3b\u9898'),
        ),
    ]
