# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='\u4e1a\u52a1\u7c7b\u578b')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel_images')),
            ],
        ),
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='\u6b66\u6c49\u5e02\u6c34\u7535\u6d4b\u8bd5\u4e2d\u5fc3', max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('address', models.CharField(default='\u6b66\u6c49\u5e02\u6c5f\u6c49\u533a\u6c34\u5229\u8def166\u53f7', max_length=100, verbose_name='\u5730\u5740')),
                ('phone_number', models.CharField(default='13807117074', max_length=20, verbose_name='\u624b\u673a')),
                ('fax', models.CharField(default='027-83620432-803', max_length=20, verbose_name='\u4f20\u771f')),
                ('url', models.CharField(default='www.whsdcszx.com', max_length=50, verbose_name='\u7f51\u5740')),
                ('profile', models.TextField(default='', max_length=1000, verbose_name='\u4e2d\u5fc3\u7b80\u4ecb')),
                ('org_structure', models.TextField(default='', max_length=1000, verbose_name='\u7ec4\u7ec7\u7ed3\u6784')),
                ('philosophy', models.TextField(default='', max_length=1000, verbose_name='\u7ecf\u8425\u7406\u5ff5')),
                ('business_info', models.TextField(default='', max_length=1000, verbose_name='\u4e1a\u52a1\u4ecb\u7ecd')),
                ('job', models.TextField(default='', max_length=2000, verbose_name='\u62db\u8058\u4fe1\u606f')),
                ('account_titles', models.CharField(default='\u6b66\u6c49\u5e02\u6c34\u7535\u6d4b\u8bd5\u4e2d\u5fc3', max_length=30, verbose_name='\u94f6\u884c\u8d26\u6237\u540d')),
                ('bank_account', models.CharField(default='17016701040003431\uff08830186\uff09', max_length=30, verbose_name='\u94f6\u884c\u8d26\u53f7')),
                ('bank_name', models.CharField(default='\u519c\u884c\u9752\u5e74\u8def\u652f\u884c', max_length=30, verbose_name='\u94f6\u884c')),
                ('ibc_num', models.CharField(default='\u9102ICP\u590714004256\u53f7', max_length=50, verbose_name='\u5907\u6848\u53f7')),
                ('postcode', models.CharField(default='460015', max_length=6, verbose_name='\u90ae\u7f16')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_created=True, verbose_name='\u7559\u8a00\u65f6\u95f4')),
                ('title', models.CharField(max_length=50, verbose_name='\u4e3b\u9898')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('phone_number', models.CharField(max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('email', models.CharField(max_length=30, verbose_name='\u7535\u5b50\u90ae\u4ef6')),
                ('content', models.TextField(max_length=500, verbose_name='\u7559\u8a00\u5185\u5bb9')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='\u65f6\u95f4')),
                ('title', models.CharField(max_length=30, verbose_name='\u4e3b\u9898')),
                ('type', models.CharField(choices=[('1', '\u884c\u4e1a\u65b0\u95fb'), ('2', '\u516c\u53f8\u65b0\u95fb')], max_length=10)),
                ('content', models.TextField(max_length=1000, verbose_name='\u5185\u5bb9')),
                ('count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='\u65f6\u95f4')),
                ('title', models.CharField(max_length=30, verbose_name='\u4e3b\u9898')),
                ('content', models.TextField(max_length=1000, verbose_name='\u5185\u5bb9')),
                ('count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Qality_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='qality_images')),
            ],
        ),
    ]
