# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='\u65f6\u95f4')),
                ('title', models.CharField(max_length=30, verbose_name='\u4e3b\u9898')),
                ('type', models.CharField(choices=[('1', '\u884c\u4e1a\u65b0\u95fb'), ('2', '\u516c\u53f8\u65b0\u95fb')], default='2', max_length=10, verbose_name='\u65b0\u95fb\u7c7b\u578b')),
                ('content', models.TextField(verbose_name='\u65b0\u95fb\u5185\u5bb9')),
                ('count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u8d44\u8baf',
                'verbose_name_plural': '\u65b0\u95fb\u8d44\u8baf',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': '\u4e1a\u52a1\u7c7b\u578b', 'verbose_name_plural': '\u4e1a\u52a1\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='carousel_image',
            options={'verbose_name': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247', 'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad\u56fe\u7247'},
        ),
        migrations.AlterModelOptions(
            name='company_profile',
            options={'verbose_name': '\u516c\u53f8\u8d44\u6599', 'verbose_name_plural': '\u516c\u53f8\u8d44\u6599'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '\u7559\u8a00', 'verbose_name_plural': '\u7559\u8a00'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u5de5\u7a0b\u4e1a\u7ee9', 'verbose_name_plural': '\u5de5\u7a0b\u4e1a\u7ee9'},
        ),
        migrations.AlterModelOptions(
            name='qality_image',
            options={'verbose_name': '\u8d44\u8d28\u56fe\u7247', 'verbose_name_plural': '\u8d44\u8d28\u56fe\u7247'},
        ),
        migrations.RemoveField(
            model_name='carousel_image',
            name='name',
        ),
        migrations.AddField(
            model_name='company_profile',
            name='telephone',
            field=models.CharField(default='027-83630193/83605046', max_length=50, verbose_name='\u8054\u7cfb\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='business',
            name='content',
            field=models.TextField(verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='carousel_image',
            name='image',
            field=models.ImageField(upload_to='carousel_images', verbose_name='\u4e0a\u4f20\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='business_info',
            field=models.TextField(default='', verbose_name='\u4e1a\u52a1\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='job',
            field=models.TextField(default='', verbose_name='\u62db\u8058\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='org_structure',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u7ec4\u7ec7\u7ed3\u6784'),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='philosophy',
            field=models.TextField(blank=True, null=True, verbose_name='\u7ecf\u8425\u7406\u5ff5'),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='profile',
            field=models.TextField(default='', verbose_name='\u4e2d\u5fc3\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='\u7559\u8a00\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='qality_image',
            name='image',
            field=models.ImageField(upload_to='qality_images', verbose_name='\u4e0a\u4f20\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='qality_image',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u8d44\u8d28\u56fe\u7247\u540d'),
        ),
    ]
