# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_auto_20180105_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='\u7559\u8a00\u65f6\u95f4'),
        ),
    ]
